# param for experiment
experiment:
  seed: 42
  data: "mhqg-wq"
  data_dir: "data/mhqg-wq/"
  model_name_or_path: "t5-small"
  tokenizer_name_or_path: "t5-small"
  model_dir: content/mhqg-wq_t5-small_20210822_1428

# モデルに関するパラメータ
model:
  max_input_length: 512
  max_target_length: 100


# 実験時に使用するパラメータ
training:
  learning_rate: 3e-4
  weight_decay: 0.0
  adam_epsilon: 1e-8
  warmup_steps: 0
  gradient_accumulation_steps: 1
  early_stop_callback: False
  fp_16: False
  opt_level: 'O1'
  max_grad_norm: 1.0
  seed: 42
  train_batch_size: 2
  eval_batch_size: 2
  num_train_epochs: 8
  precision: 16
  n_gpu: 1