# param for experiment
# 実験実施のためのパラメータ
experiment:
  seed: 42
  data: "mhqg-wq"
  data_dir: "data/mhqg-wq/"
  model_name_or_path: "t5-small"
  tokenizer_name_or_path: "t5-small"
  model_dir: content/test_mhqg-wq_t5-small_with_TripleAttention_20210918_1218
  wandb:
    exp_num: 001
    project: test_mhqg-wq_t5-small_with_TripleAttention
    checkpoint_path: checkpoint/

# param for model    
# モデルに関するパラメータ
model:
  max_input_length: 100
  max_target_length: 100

# param for training
# 実験時に使用するパラメータ
training:
  learning_rate: 3e-4
  weight_decay: 0.0
  adam_epsilon: 1e-8
  warmup_steps: 0
  gradient_accumulation_steps: 1
  # early_stop_callback: False
  early_stop_callback: True
  fp_16: False
  # fp_16: True
  opt_level: 'O1'
  max_grad_norm: 1.0
  seed: 42
  train_batch_size: 32
  eval_batch_size: 32
  test_batch_size: 8
  num_train_epochs: 10
  precision: 16
  n_gpu: 1